apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-customer
  namespace: framely-stage
  labels:
    app: frontend-customer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-customer
  template:
    metadata:
      labels:
        app: frontend-customer
    spec:
      containers:
        - name: frontend-customer
          image: framely-frontend-customer:latest
          # Image tag managed via Kustomize (GitOps)

          ports:
            - containerPort: 3000

          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
