apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: framely-stage-ingress
  namespace: framely-stage
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: api.framely.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80

    - host: admin.framely.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-admin
                port:
                  number: 80

    - host: app.framely.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-customer
                port:
                  number: 80
